version: '3'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - my-network
  my-spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqlcontainer:3306/kowenJava
      SPRING_DATASOURCE_USERNAME: sammy
      SPRING_DATASOURCE_PASSWORD: A4t474357oC5$77u5
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - my-network
volumes:
  mysql-data:
networks:
  my-network: